export interface DersKayitDetayDto{
    id:number
    ogrenciId:number
    ogrenciAdi:string
    ogrenciSoyadi:string
    ogrenciNo:number
    ogrenciMail:string
    danismanId:number
    danismanAdi:string
    danismanSoyadi:string
    danismanMail:string
    dersId1:number
    dersAdi1:string
    dersKodu1:string
    dersId2:number
    dersAdi2:string
    dersKodu2:string
    dersId3:number
    dersAdi3:string
    dersKodu3:string
    dersId4:number
    dersAdi4:string
    dersKodu4:string
    dersId5:number
    dersAdi5:string
    dersKodu5:string
    dersId6:number
    dersAdi6:string
    dersKodu6:string
    dersId7:number
    dersAdi7:string
    dersKodu7:string
    dersId8:number
    dersAdi8:string
    dersKodu8:string
    dersId9:number
    dersAdi9:string
    dersKodu9:string
    dersId10:number
    dersAdi10:string
    dersKodu10:string
    onayDurumu:boolean
}